//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Auditoria.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AuditoriaPOAEntities4 : DbContext
    {
        public AuditoriaPOAEntities4()
            : base("name=AuditoriaPOAEntities4")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Digitadores> Digitadores { get; set; }
        public virtual DbSet<Entrevista> Entrevista { get; set; }
        public virtual DbSet<Indicadores> Indicadores { get; set; }
        public virtual DbSet<P10Re> P10Re { get; set; }
        public virtual DbSet<P12Re> P12Re { get; set; }
        public virtual DbSet<P1Sexo> P1Sexo { get; set; }
        public virtual DbSet<P2Re> P2Re { get; set; }
        public virtual DbSet<P3bRe> P3bRe { get; set; }
        public virtual DbSet<P4Re> P4Re { get; set; }
        public virtual DbSet<P7Re> P7Re { get; set; }
        public virtual DbSet<Provincias> Provincias { get; set; }
        public virtual DbSet<Regiones> Regiones { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Table_1> Table_1 { get; set; }
        public virtual DbSet<Visitas> Visitas { get; set; }
    }
}
