//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Auditoria.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table_1
    {
        public int NCuest { get; set; }
        public int Trimestre { get; set; }
        public int Año { get; set; }
        public int Region { get; set; }
        public int Provincia { get; set; }
        public Nullable<int> Municipio { get; set; }
        public Nullable<int> DistritoMunicipal { get; set; }
        public string PersonaEntrevistada { get; set; }
        public string Responsable { get; set; }
        public int P1 { get; set; }
        public int P2 { get; set; }
        public int P3a { get; set; }
        public int P3b { get; set; }
        public Nullable<int> P4 { get; set; }
        public string P5 { get; set; }
        public string P6 { get; set; }
        public Nullable<int> P7 { get; set; }
        public string P8 { get; set; }
        public string P9 { get; set; }
        public int P10 { get; set; }
        public string P11 { get; set; }
        public int P12 { get; set; }
        public string P12b { get; set; }
        public Nullable<int> P13 { get; set; }
        public string P14 { get; set; }
        public System.DateTime Time { get; set; }
        public int Digitador { get; set; }
        public string Dia { get; set; }
        public string Mes { get; set; }
    
        public virtual Digitadores Digitadores { get; set; }
        public virtual Indicadores Indicadores { get; set; }
        public virtual P10Re P10Re { get; set; }
        public virtual P12Re P12Re { get; set; }
        public virtual P1Sexo P1Sexo { get; set; }
        public virtual P2Re P2Re { get; set; }
        public virtual P3bRe P3bRe { get; set; }
        public virtual P4Re P4Re { get; set; }
        public virtual P7Re P7Re { get; set; }
        public virtual Provincias Provincias { get; set; }
        public virtual Regiones Regiones { get; set; }
        public virtual Visitas Visitas { get; set; }
    }
}
